package store

import (
 "context"; "encoding/json"; "errors"; "time"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/nawyaunnam/cloudscale-distributed-job-processing/internal/model"
)
type Store struct{ DB *pgxpool.Pool }
func New(ctx context.Context, url string)(*Store,error){ db,e:=pgxpool.New(ctx,url); if e!=nil{return nil,e}; s:=&Store{db}; e=s.Migrate(ctx); return s,e }
func(s *Store)Migrate(ctx context.Context)error{_,e:=s.DB.Exec(ctx,`CREATE TABLE IF NOT EXISTS jobs(id uuid primary key,tenant_id text not null,type text not null,payload jsonb not null,status text not null,attempt int not null default 0,max_attempts int not null default 4,idempotency_key text,lease_owner text,lease_expires_at timestamptz,result jsonb,error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,idempotency_key)); CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs(status,created_at);`);return e}
func(s *Store)Create(ctx context.Context,j model.Job,key string)(model.Job,bool,error){ p,_:=json.Marshal(j.Payload); row:=s.DB.QueryRow(ctx,`INSERT INTO jobs(id,tenant_id,type,payload,status,max_attempts,idempotency_key) VALUES($1,$2,$3,$4,'queued',$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET updated_at=jobs.updated_at RETURNING id,tenant_id,type,payload,status,attempt,max_attempts,created_at,updated_at`,j.ID,j.TenantID,j.Type,p,j.MaxAttempts,key); e:=row.Scan(&j.ID,&j.TenantID,&j.Type,&j.Payload,&j.Status,&j.Attempt,&j.MaxAttempts,&j.CreatedAt,&j.UpdatedAt); return j,e==nil&&j.ID!="",e}
func(s *Store)Get(ctx context.Context,id,tenant string)(model.Job,error){var j model.Job; var result []byte; e:=s.DB.QueryRow(ctx,`SELECT id,tenant_id,type,payload,status,attempt,max_attempts,created_at,updated_at,COALESCE(error,''),COALESCE(result,'{}') FROM jobs WHERE id=$1 AND tenant_id=$2`,id,tenant).Scan(&j.ID,&j.TenantID,&j.Type,&j.Payload,&j.Status,&j.Attempt,&j.MaxAttempts,&j.CreatedAt,&j.UpdatedAt,&j.Error,&result); json.Unmarshal(result,&j.Result); return j,e}
func(s *Store)Lease(ctx context.Context,id,worker string,d time.Duration)(model.Job,error){var j model.Job; e:=s.DB.QueryRow(ctx,`UPDATE jobs SET status='running',attempt=attempt+1,lease_owner=$2,lease_expires_at=now()+$3::interval,updated_at=now() WHERE id=$1 AND status IN ('queued','retrying') RETURNING id,tenant_id,type,payload,status,attempt,max_attempts,created_at,updated_at`,id,worker,d.String()).Scan(&j.ID,&j.TenantID,&j.Type,&j.Payload,&j.Status,&j.Attempt,&j.MaxAttempts,&j.CreatedAt,&j.UpdatedAt); return j,e}
func(s *Store)Heartbeat(ctx context.Context,id,worker string,d time.Duration)error{tag,e:=s.DB.Exec(ctx,`UPDATE jobs SET lease_expires_at=now()+$3::interval,updated_at=now() WHERE id=$1 AND lease_owner=$2 AND status='running'`,id,worker,d.String());if e==nil&&tag.RowsAffected()==0{return errors.New("lease lost")};return e}
func(s *Store)Complete(ctx context.Context,id,worker string,result map[string]any)error{b,_:=json.Marshal(result);_,e:=s.DB.Exec(ctx,`UPDATE jobs SET status='succeeded',result=$3,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2`,id,worker,b);return e}
func(s *Store)Fail(ctx context.Context,id,worker,msg string,retry bool)error{status:="dead_letter";if retry{status="retrying"};_,e:=s.DB.Exec(ctx,`UPDATE jobs SET status=$3,error=$4,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2`,id,worker,status,msg);return e}
func(s *Store)Recover(ctx context.Context)([]string,error){rows,e:=s.DB.Query(ctx,`UPDATE jobs SET status='retrying',lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE status='running' AND lease_expires_at<now() RETURNING id`);if e!=nil{return nil,e};defer rows.Close();var ids []string;for rows.Next(){var id string;rows.Scan(&id);ids=append(ids,id)};return ids,rows.Err()}

